In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load the dataset
from sklearn.datasets import load_diabetes

In [3]:
load_diabetes()

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [ ]:
# convert above dict data into dataframe

In [4]:
data_temp= load_diabetes()

In [5]:
data_temp.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [6]:
data_temp.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [9]:
data_temp.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
       197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
        59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
       237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
       143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
       142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
        77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
        78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
       154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
        71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
       150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
       145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
        94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
        60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
        31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
       114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
       191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
       244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
       263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
        77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
        58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
       140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
       219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
        43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
       140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
        84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
        94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
       220.,  57.])

In [7]:
df= pd.DataFrame(data_temp.data, columns=data_temp.feature_names)

In [8]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [10]:
print(data_temp.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

:Number of Instances: 442

:Number of Attributes: First 10 columns are numeric predictive values

:Target: Column 11 is a quantitative measure of disease progression one year after baseline

:Attribute Information:
    - age     age in years
    - sex
    - bmi     body mass index
    - bp      average blood pressure
    - s1      tc, total serum cholesterol
    - s2      ldl, low-density lipoproteins
    - s3      hdl, high-density lipoproteins
    - s4      tch, total cholesterol / HDL
    - s5      ltg, possibly log of serum triglycerides level
    - s6      glu, blood sugar level

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.
(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)

In [ ]:
# add target variable in dataframe

In [45]:
df['target']= data_temp.target
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [ ]:
# now dependent and independent both variables present in dataset

In [ ]:
# 1. data cleaning

In [ ]:
# rules of regression model for data cleaning
# 1. no categorical data should be present in dataframe in regression: passed
# 2. no missing values should be present
# 3. no special symbols should be presnet

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
 10  target  442 non-null    float64
dtypes: float64(11)
memory usage: 38.1 KB

In [ ]:
# no null values, no categorical data , no special symbols
# as info gives non null values total 442 in each column and data typoe also float for all columns

In [ ]:
# 2. eda 
# perform feature corelation: they are linear or non- linear, plots draw - see distribution of data, predict outlier , handle outliers by interquartile range , z score method

In [ ]:
# simple linear regression model training

In [ ]:
# simple linear reg we have only one independent variable

In [12]:
X= df[['bmi']] #independent var
Y= df[['target']] #dependent var

In [ ]:
# decide training data and testing data

In [ ]:
# all the models are present in sklearn library
# take all below code from sklearn official documentation 
# search eg: sklearn train_test_split

In [13]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size=0.2, random_state=42)

In [15]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((353, 1), (89, 1), (353, 1), (89, 1))

In [ ]:
# 1. First understand (353, 1)

# A shape is written as:

# (number of rows, number of columns)

# So:

# (353, 1)

# means:

# 353 rows/data records
# 1 column/feature
# 2. Your four outputs
# X_train.shape
# (353, 1)

# Means:

# 353 training records and 1 input feature.

# For example:

# X_train

#    X
#    ↓
# [ 10 ]
# [ 20 ]
# [ 15 ]
# [ 30 ]
# ...
# [353 rows]
# X_test.shape
# (89, 1)

# Means:

# 89 testing records and 1 input feature.

# X_test

#    X
#    ↓
# [ 25 ]
# [ 18 ]
# [ 40 ]
# ...
# [89 rows]
# Y_train.shape
# (353, 1)

# Means:

# 353 actual target values corresponding to the 353 training inputs.

# X_train              Y_train

# 10  ───────────────→  50
# 20  ───────────────→  70
# 15  ───────────────→  60
# 30  ───────────────→  90

# So:

# $$ \boxed{X_{train} \leftrightarrow Y_{train}} $$

# They have the same 353 rows because each X must have its corresponding Y.

# Y_test.shape
# (89, 1)

# Means:

# 89 actual target values corresponding to the 89 test inputs.

# X_test              Y_test

# 25  ──────────────→  75
# 18  ──────────────→  55
# 40  ──────────────→  95
# 3. Why 353 + 89 = 442?

# Your complete dataset has:

# $$ 353+89=442 $$

# So you originally have 442 records.

# You specified:

# test_size=0.2

# meaning 20% for testing.

# 20% of 442:

# $$ 442\times0.2=88.4 $$

# Since we cannot have 0.4 of a row, it becomes 89 test rows.

# Remaining:

# $$ 442-89=353 $$

# So:

#              442 TOTAL RECORDS
#                     │
#           ┌─────────┴─────────┐
#           ↓                   ↓
#        80%                  20%
#     TRAINING               TESTING
#        353                   89
#         │                     │
#         ↓                     ↓
#    X_train + Y_train     X_test + Y_test
#     (353,1)  (353,1)      (89,1)  (89,1)
# 4. Why is there 1 after the comma?

# Because you have one feature/input column.

# For Simple Linear Regression, you have only one X variable.

# For example:

# Hours Studied
# 2
# 4
# 6
# 8

# Then:

# X.shape

# would be:

# (4, 1)

# because:

# 4 rows
# 1 feature

# If you had 3 input features, it could look like:

# (442, 3)

# For example:

# Age	Experience	Education
# 22	1	16
# 25	3	16
# 28	5	18

# Then there are:

# 442 rows
# 3 columns/features
# ⭐ Most important thing to remember

# Your output:

# ((353, 1), (89, 1), (353, 1), (89, 1))

# means:

# Variable	Meaning
# X_train	353 input values used for training
# X_test	89 input values kept for testing
# Y_train	353 actual answers used during training
# Y_test	89 actual answers kept for comparison during testing

# And the 89 test rows are unseen by the model during training.

# Later:

# model.fit(X_train, Y_train)

# ⬆️ Model learns from 353 X + 353 Y

# Then:

# Y_pred = model.predict(X_test)

# ⬆️ Model receives the 89 unseen X values and produces 89 predicted Y values.

# Finally:

# Y_test       vs       Y_pred
# Actual                Predicted
#   89 values             89 values

# That's where your actual vs predicted comparison happens. 🎯

In [ ]:
# train simple linear reg model

In [16]:
from sklearn.linear_model import LinearRegression

In [ ]:
# model initilized , all parameters of linerregression() function is set to default as given in sklearn simple linear reg documentation
lr_simple = LinearRegression()

In [19]:
# train model using fit function
lr_simple.fit(X_train, Y_train)

LinearRegression()

In [ ]:
# other parameters setted by default , no need to explicitly set it

In [27]:
# test model by testing data 
# indepoendent var X-test passed and dependent var Y_test is returned as answers 
y_pred_simple_test= lr_simple.predict(X_test)

In [28]:
y_pred_simple_test

array([[145.80622687],
       [188.85739048],
       [147.95878505],
       [203.92529774],
       [131.8145987 ],
       [127.50948234],
       [322.31599764],
       [197.4676232 ],
       [ 61.85645785],
       [167.33180868],
       [118.89924962],
       [ 94.14483055],
       [ 90.91599328],
       [166.25552959],
       [ 96.29738873],
       [157.64529687],
       [223.29832136],
       [240.5187868 ],
       [180.24715776],
       [210.38297228],
       [191.00994866],
       [109.21273781],
       [102.75506327],
       [174.86576231],
       [196.39134411],
       [166.25552959],
       [211.45925137],
       [133.96715688],
       [ 78.0006442 ],
       [130.73831961],
       [244.82390316],
       [114.59413326],
       [166.25552959],
       [145.80622687],
       [192.08622775],
       [229.7559959 ],
       [121.0518078 ],
       [118.89924962],
       [121.0518078 ],
       [ 94.14483055],
       [ 82.30576056],
       [122.12808689],
       [129.66204052],
       [118.89924962],
       [107.06017963],
       [116.74669144],
       [115.67041235],
       [101.67878418],
       [ 67.2378533 ],
       [153.34018051],
       [210.38297228],
       [ 82.30576056],
       [169.48436686],
       [111.36529599],
       [133.96715688],
       [216.84064682],
       [105.98390054],
       [213.61180955],
       [133.96715688],
       [ 97.37366782],
       [182.39971594],
       [193.16250684],
       [206.07785592],
       [107.06017963],
       [ 86.61087692],
       [170.56064595],
       [140.42483142],
       [127.50948234],
       [117.82297053],
       [139.34855233],
       [133.96715688],
       [182.39971594],
       [130.73831961],
       [141.50111051],
       [ 90.91599328],
       [112.44157508],
       [212.53553046],
       [191.00994866],
       [171.63692504],
       [131.8145987 ],
       [147.95878505],
       [140.42483142],
       [ 87.68715601],
       [ 91.99227237],
       [ 86.61087692],
       [126.43320325],
       [ 88.7634351 ],
       [ 82.30576056],
       [187.78111139]])

In [ ]:
# evaluation parameters : mse, mae, rmse, r square , adjusted r square
# check overfitting and underfitting also to do so we have to predict model on training data also so that we can decide model works good with which data and model is overfitted underfitted or generalizwed

In [29]:
y_pred_simple_train= lr_simple.predict(X_train)

In [21]:
y_pred_simple_train

array([[164.10297141],
       [133.96715688],
       [201.77273956],
       [116.74669144],
       [ 86.61087692],
       [112.44157508],
       [172.71320413],
       [221.14576318],
       [189.93366957],
       [135.04343597],
       [ 83.38203965],
       [171.63692504],
       [ 94.14483055],
       [256.66297315],
       [ 72.61924875],
       [172.71320413],
       [111.36529599],
       [116.74669144],
       [108.13645872],
       [171.63692504],
       [178.09459958],
       [115.67041235],
       [194.23878593],
       [101.67878418],
       [207.15413501],
       [166.25552959],
       [140.42483142],
       [141.50111051],
       [142.5773896 ],
       [147.95878505],
       [167.33180868],
       [175.9420414 ],
       [114.59413326],
       [119.97552871],
       [170.56064595],
       [136.11971506],
       [145.80622687],
       [160.87413414],
       [114.59413326],
       [142.5773896 ],
       [ 74.77180693],
       [150.11134323],
       [107.06017963],
       [197.4676232 ],
       [184.55227412],
       [237.28994953],
       [141.50111051],
       [262.0443686 ],
       [145.80622687],
       [153.34018051],
       [266.34948496],
       [111.36529599],
       [169.48436686],
       [211.45925137],
       [105.98390054],
       [199.62018138],
       [157.64529687],
       [121.0518078 ],
       [206.07785592],
       [146.88250596],
       [142.5773896 ],
       [177.01832049],
       [280.34111313],
       [166.25552959],
       [151.18762232],
       [121.0518078 ],
       [156.56901778],
       [161.95041323],
       [121.0518078 ],
       [113.51785417],
       [154.4164596 ],
       [126.43320325],
       [ 85.53459783],
       [112.44157508],
       [104.90762145],
       [119.97552871],
       [154.4164596 ],
       [197.4676232 ],
       [ 97.37366782],
       [113.51785417],
       [136.11971506],
       [140.42483142],
       [ 62.93273694],
       [126.43320325],
       [174.86576231],
       [213.61180955],
       [144.72994778],
       [231.90855408],
       [212.53553046],
       [208.2304141 ],
       [126.43320325],
       [156.56901778],
       [158.72157596],
       [124.28064507],
       [104.90762145],
       [147.95878505],
       [112.44157508],
       [ 86.61087692],
       [222.22204227],
       [179.17087867],
       [175.9420414 ],
       [ 68.31413239],
       [223.29832136],
       [193.16250684],
       [129.66204052],
       [223.29832136],
       [ 93.06855146],
       [221.14576318],
       [158.72157596],
       [168.40808777],
       [206.07785592],
       [110.2890169 ],
       [192.08622775],
       [220.06948409],
       [ 93.06855146],
       [103.83134236],
       [127.50948234],
       [224.37460045],
       [ 70.46669057],
       [244.82390316],
       [196.39134411],
       [156.56901778],
       [ 96.29738873],
       [105.98390054],
       [122.12808689],
       [186.7048323 ],
       [138.27227324],
       [161.95041323],
       [157.64529687],
       [103.83134236],
       [117.82297053],
       [126.43320325],
       [240.5187868 ],
       [158.72157596],
       [122.12808689],
       [212.53553046],
       [163.02669232],
       [198.54390229],
       [232.98483317],
       [185.62855321],
       [153.34018051],
       [157.64529687],
       [137.19599415],
       [191.00994866],
       [256.66297315],
       [279.26483404],
       [216.84064682],
       [122.12808689],
       [144.72994778],
       [199.62018138],
       [143.65366869],
       [211.45925137],
       [118.89924962],
       [ 89.83971419],
       [128.58576143],
       [139.34855233],
       [ 76.92436511],
       [142.5773896 ],
       [110.2890169 ],
       [168.40808777],
       [240.5187868 ],
       [154.4164596 ],
       [207.15413501],
       [104.90762145],
       [116.74669144],
       [128.58576143],
       [192.08622775],
       [141.50111051],
       [173.78948322],
       [172.71320413],
       [136.11971506],
       [160.87413414],
       [138.27227324],
       [228.67971681],
       [111.36529599],
       [158.72157596],
       [188.85739048],
       [127.50948234],
       [132.89087779],
       [ 70.46669057],
       [155.49273869],
       [127.50948234],
       [152.26390142],
       [153.34018051],
       [156.56901778],
       [ 85.53459783],
       [118.89924962],
       [143.65366869],
       [150.11134323],
       [113.51785417],
       [201.77273956],
       [122.12808689],
       [ 98.44994691],
       [213.61180955],
       [220.06948409],
       [ 71.54296966],
       [127.50948234],
       [ 99.526226  ],
       [223.29832136],
       [128.58576143],
       [194.23878593],
       [195.31506502],
       [123.20436598],
       [121.0518078 ],
       [130.73831961],
       [131.8145987 ],
       [164.10297141],
       [ 80.15320238],
       [185.62855321],
       [113.51785417],
       [ 94.14483055],
       [168.40808777],
       [226.52715863],
       [ 95.22110964],
       [237.28994953],
       [143.65366869],
       [ 84.45831874],
       [115.67041235],
       [178.09459958],
       [146.88250596],
       [208.2304141 ],
       [113.51785417],
       [115.67041235],
       [312.62948583],
       [121.0518078 ],
       [169.48436686],
       [105.98390054],
       [161.95041323],
       [ 81.22948147],
       [105.98390054],
       [146.88250596],
       [129.66204052],
       [245.90018225],
       [156.56901778],
       [ 79.07692329],
       [277.11227586],
       [151.18762232],
       [ 94.14483055],
       [170.56064595],
       [211.45925137],
       [123.20436598],
       [223.29832136],
       [143.65366869],
       [135.04343597],
       [182.39971594],
       [149.03506414],
       [263.12064769],
       [144.72994778],
       [208.2304141 ],
       [ 89.83971419],
       [213.61180955],
       [143.65366869],
       [126.43320325],
       [225.45087954],
       [126.43320325],
       [141.50111051],
       [143.65366869],
       [274.95971768],
       [201.77273956],
       [187.78111139],
       [127.50948234],
       [212.53553046],
       [139.34855233],
       [158.72157596],
       [197.4676232 ],
       [155.49273869],
       [191.00994866],
       [249.12901952],
       [250.20529861],
       [121.0518078 ],
       [206.07785592],
       [186.7048323 ],
       [212.53553046],
       [119.97552871],
       [ 96.29738873],
       [215.76436773],
       [128.58576143],
       [183.47599503],
       [139.34855233],
       [153.34018051],
       [115.67041235],
       [119.97552871],
       [136.11971506],
       [100.60250509],
       [117.82297053],
       [166.25552959],
       [164.10297141],
       [198.54390229],
       [ 88.7634351 ],
       [ 74.77180693],
       [288.95134585],
       [203.92529774],
       [144.72994778],
       [142.5773896 ],
       [149.03506414],
       [180.24715776],
       [143.65366869],
       [150.11134323],
       [131.8145987 ],
       [111.36529599],
       [167.33180868],
       [131.8145987 ],
       [ 91.99227237],
       [218.993205  ],
       [153.34018051],
       [195.31506502],
       [150.11134323],
       [163.02669232],
       [156.56901778],
       [105.98390054],
       [177.01832049],
       [127.50948234],
       [144.72994778],
       [161.95041323],
       [ 85.53459783],
       [136.11971506],
       [ 97.37366782],
       [125.35692416],
       [ 87.68715601],
       [110.2890169 ],
       [140.42483142],
       [137.19599415],
       [211.45925137],
       [129.66204052],
       [205.00157683],
       [ 89.83971419],
       [178.09459958],
       [110.2890169 ],
       [132.89087779],
       [244.82390316],
       [151.18762232],
       [170.56064595],
       [ 96.29738873],
       [105.98390054],
       [146.88250596],
       [248.05274043],
       [147.95878505],
       [157.64529687],
       [ 87.68715601],
       [128.58576143],
       [145.80622687],
       [182.39971594],
       [118.89924962],
       [169.48436686],
       [ 79.07692329],
       [ 95.22110964],
       [149.03506414],
       [185.62855321],
       [ 75.84808602],
       [182.39971594],
       [131.8145987 ],
       [128.58576143],
       [180.24715776]])

In [22]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:

# error: predicted - actual 
 
# training data error
# error= y_train - y_pred_train_data
# testing data error
# error = y_test- y_pred_test_data

# means take diff of actual value and predicted values in both case training and testing also

In [33]:
# training data 
print("MSE:", mean_squared_error(Y_train, y_pred_simple_train))
print("MAE:", mean_absolute_error(Y_train, y_pred_simple_train))
print("RMSE:", np.sqrt(mean_squared_error(Y_train, y_pred_simple_train)))
print("R2:", r2_score(Y_train, y_pred_simple_train))

MSE: 3854.11265207582
MAE: 51.37972765404719
RMSE: 62.081500079136454
R2: 0.3657241273794126

In [34]:
# testing data 
print("MSE:", mean_squared_error(Y_test, y_pred_simple_test))
print("MAE:", mean_absolute_error(Y_test, y_pred_simple_test))
print("RMSE:", np.sqrt(mean_squared_error(Y_test, y_pred_simple_test)))
print("R2:", r2_score(Y_test, y_pred_simple_test))

MSE: 4061.8259284949268
MAE: 52.25997644534553
RMSE: 63.73245584860925
R2: 0.23335039815872138

In [ ]:
# R2 value is 0.23 means the y var explains 23 % variance of x var

In [ ]:
# UNDERFITTING
# Training Error → HIGH
# Testing Error  → HIGH
#         ↓
# Didn't learn enough


# OVERFITTING
# Training Error → LOW
# Testing Error  → HIGH
#         ↓
# Memorized training data


# GENERALIZED MODEL
# Training Error → LOW
# Testing Error  → LOW
#         ↓
# Learned the general pattern

In [ ]:
# Use training vs testing performance.

# Case	    Training result	  Testing result	          Conclusion
# Underfitting	Poor	        Poor 	          Model is too simple
# Overfitting	Very good	  Much worse             	Model memorized training data
# Generalized	Good	   Good and close to training	  Model works on unseen dat


# For error metrics such as RMSE(error):
# Lower is better.
# Compare the gap between training and testing RMSE.
# For R2
# Higher is better.
# Compare the training and testing values.

In [ ]:
# checke rmse (error), r2 how much y descibes x , how much the trauing and testing data values is close 
# rmse should be low and r2 should be high and both training and testing data valeus of r2 and rmse should be close then model is generalized

In [ ]:
# The training and testing results are close, so the model is not overfitted and generalizes reasonably well. 
# R2 value is higher in training data , and rmse value is lower in training data only, and values are close in both training and testing 
# as in table given if traing data good and testing data also good and close to training meand model is generalized model.
# However, both R2 values are low, meaning the model has weak predictive power. Because it uses only bmi, it may be somewhat underfit.

In [55]:
def adjusted_r2(r2, n, k):
    return 1 - ((1 - r2) * (n - 1) / (n - k - 1))

In [ ]:
# multiple linear reg: adjusted r2  is used when there are multiple x independent features

In [ ]:

X= df.drop('target', axis= 1) # all features passed as X as it is multiple reg except target
Y= df['target']

In [39]:
X

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [40]:
Y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split( X, Y, test_size=0.2, random_state=42)

In [43]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((353, 10), (89, 10), (353,), (89,))

In [44]:
lr_multi = LinearRegression()

In [46]:
lr_multi.fit(X_train, Y_train)

LinearRegression()

In [47]:
y_pred_multi_test= lr_multi.predict( X_test)
y_pred_multi_train= lr_multi.predict( X_train)

In [58]:
# training data 
print("MSE:", mean_squared_error(Y_train, y_pred_multi_train))
print("MAE:", mean_absolute_error(Y_train, y_pred_multi_train))
print("RMSE:", np.sqrt(mean_squared_error(Y_train, y_pred_multi_train)))
print("R2:", r2_score(Y_train, y_pred_multi_train))

# function defined upside is called with values of R2, n and k 
print(
    "Adjusted R2:",
    adjusted_r2(
        r2_score(Y_train, y_pred_multi_train),
        X_train.shape[0],
        X_train.shape[1]
    )
)

# Here:

# n = number of observations
# k = number of independent variables
# r2 = ordinary R2

# The adjusted 
# R2 is useful for multiple regression because it penalizes adding unnecessary features.

MSE: 2868.549702835578
MAE: 43.483503523980396
RMSE: 53.55884336723094
R2: 0.5279193863361497
Adjusted R2: 0.5141158596208324

In [60]:
# testing data 
print("MSE:", mean_squared_error(Y_test, y_pred_multi_test))
print("MAE:", mean_absolute_error(Y_test, y_pred_multi_test))
print("RMSE:", np.sqrt(mean_squared_error(Y_test, y_pred_multi_test)))
print("R2:", r2_score(Y_test, y_pred_multi_test))

print(
    "Adjusted R2:",
    adjusted_r2(
        r2_score(Y_test, y_pred_multi_test),
        X_test.shape[0],
        X_test.shape[1]
    )
)

MSE: 2900.1936284934814
MAE: 42.79409467959994
RMSE: 53.85344583676593
R2: 0.4526027629719195
Adjusted R2: 0.38242363001960145

In [ ]:
# Your results show a generalized model:

# Metric    	Training	Testing
# RMSE	      53.56	   53.85
# MAE	          43.48    42.79
# R2            0.528	   0.453
# Adjusted R2   0.514	   0.382


# Conclusion
# Training and testing RMSE are almost identical.
# Testing R2 is slightly lower than training R2
#  , which is normal.
# There is no large difference between training and testing performance.
# Therefore, the model is not overfitted.
# It is also not clearly underfitted because it explains about 45% of the target variation on unseen data.
# Final conclusion: Your multiple linear regression model generalizes reasonably well. It has moderate predictive performance.

In [ ]:
# Derive the conclusion by comparing training and testing performance.

# 1. Compare RMSE
# For RMSE, lower is better:
# Training RMSE: 53.56
# Testing RMSE:  53.85
# Difference:     0.29
# The difference is very small, so the model performs almost the same on unseen data. This is evidence that it is not overfitted.



# 2. Compare 
# 𝑅2
 
# For R2
#  , higher is better:


# The testing score is lower, which is normal. The model still explains about 45.3% of the variation in unseen target values.



# 3. Check for overfitting
# Overfitting would look like this:
# Training RMSE: very low
# Testing RMSE:  much higher

# Your RMSE values are almost equal:
# 53.56 ≈ 53.85

# Therefore, there is no strong evidence of overfitting.


# 4. Check for underfitting
# Underfitting usually means both training and testing scores are poor. Your model has moderate performance:
# Testing R² = 0.453

# So it is not clearly underfitted, although it does not explain all the target variation.


# Conclusion
# The training and testing errors are nearly equal and they are low (rmse), and the testing R2 remains reasonably strong, high and close . Therefore, the model generalizes well and is not overfitted. Its predictive performance is moderate because it explains approximately 45.3% of the variation in unseen data.

# The adjusted R2
#   difference should not be the main basis for comparison because the training set has 353 observations while the testing set has only 89 observations

In [ ]:
# Ordinary R2
#   always stays the same or increases when features are added, even if those features are not useful. Adjusted R2
#   applies a penalty for unnecessary features.

# Formula:

#  1 - ((1 - r2) * (n - 1) / (n - k - 1)
# Where:

# R2= ordinary coefficient of determination
# n
# n = number of observations
# k
# k = number of independent variables

# Example from your model

# Training adjusted R²: 0.514
# Testing adjusted R²:  0.382
# This means that after considering the number of input features, the model explains approximately:

# 51.4% of training variation
# 38.2% of testing variation
# Use adjusted R2
#   mainly when comparing multiple regression models with different numbers of features. A higher adjusted R2
#   generally indicates a better balance between predictive power and model complexity.