In [ ]:
# dataframe creation using dict

In [1]:
import pandas as pd

In [3]:
data= {'name': ['abc', 'pqr', 'xyz'],
       'age' : [23,24,12]
       }

In [4]:
df= pd.DataFrame(data)
df

  name  age
0  abc   23
1  pqr   24
2  xyz   12

In [6]:
# changing index value means row label
d1= pd.DataFrame(data, index=['Mon', 'Tue', 'Wed'])
d1

    name  age
Mon  abc   23
Tue  pqr   24
Wed  xyz   12

In [7]:
# selecting columns 
d2 = pd.DataFrame(data, index=['Mon', 'Tue', 'Wed'], columns=['age'])
d2

     age
Mon   23
Tue   24
Wed   12

In [9]:
# change the sequence of columns
d3 = pd.DataFrame(data, index=['Mon', 'Tue', 'Wed'], columns=['age', 'name'])
d3

     age name
Mon   23  abc
Tue   24  pqr
Wed   12  xyz

In [ ]:
# dataframe from series
# series- dict - dataframe

In [10]:
s1= pd.Series([1,2,3], index=['a','b','c'])
s1

a    1
b    2
c    3
dtype: int64

In [12]:
dict= {'Sales':s1}
dict

{'Sales': a    1
 b    2
 c    3
 dtype: int64}

In [13]:
d1= pd.DataFrame(dict)
d1

   Sales
a      1
b      2
c      3

In [14]:
profit= pd.Series([100,200,300], index=['a','b','d'])
profit

a    100
b    200
d    300
dtype: int64

In [15]:
# combine two series to create a dataframe
dict= {'Sales':s1, 'Profit':profit}
d2= pd.DataFrame(dict)
d2

   Sales  Profit
a    1.0   100.0
b    2.0   200.0
c    3.0     NaN
d    NaN   300.0

In [23]:
dict= {'Sales':s1, 'Profit':profit}
d2= pd.DataFrame(dict, index=['a','b','e'])
d2

   Sales  Profit
a    1.0   100.0
b    2.0   200.0
e    NaN     NaN

In [20]:
d2

   Sales  Profit
a    1.0   100.0
b    2.0   200.0
e    NaN     NaN

In [21]:
# adding one column in df and it have static value for all rows
d2['Currency']= "Dollar"
d2

   Sales  Profit Currency
a    1.0   100.0   Dollar
b    2.0   200.0   Dollar
e    NaN     NaN   Dollar

In [ ]:
# nested dict- dataframe

In [22]:
nested= { 'Maths': {'S1': 46, 'S2': 78, 'S3': 90},
          'Science': {'S1': 56, 'S2': 88, 'S3': 80}
}
nested

{'Maths': {'S1': 46, 'S2': 78, 'S3': 90},
 'Science': {'S1': 56, 'S2': 88, 'S3': 80}}

In [ ]:
# column label= outer dict key 
# row label = inner dict key
df= pd.DataFrame(nested)
df

    Maths  Science
S1     46       56
S2     78       88
S3     90       80

In [ ]:
# some operation on data
# merge, join , concatenate, append, pivot, melt, stack, unstack, groupby, resample, rolling
# we can take data from multiple sources such as database, excelsheet and then process it using pandas using dataframe

In [ ]:
# merge- combine two dataframes based on common column or index
# sql join- inner, left, right, outer

In [34]:
df1= pd.DataFrame({'id':[1,2,3,4], 'name':['abc', 'pqr', 'xyz', 'lmn']})
df2= pd.DataFrame({'id':[1,2,3,5], 'score':[23,24,12, 45]})
df3= pd.DataFrame({'id':[1,2,3,4], 'score':[23,24,12, 45]})
df4= pd.DataFrame({'id':[1,2,3,5], 'score':[23,24,12, 45]})

In [ ]:
#1. merge(left table, right table, how= inner, left, right, outer, on= common column name)
# like sql there is no comp that two tables to be joined should have same column name to join 2 tables to give in on cond , if not then we can use left_on and right_on to specify the column name of left and right table

In [28]:
merged_df= pd.merge(df1, df2, on='id', how='inner')
merged_df

   id name  score
0   1  abc     23
1   2  pqr     24
2   3  xyz     12

In [32]:
merged_df= pd.merge(df1, df3, on='id', how='inner')
merged_df

   id name  score
0   1  abc     23
1   2  pqr     24
2   3  xyz     12
3   4  lmn     45

In [37]:
merged_df= pd.merge(df2, df4, on='id', how='inner')
merged_df

   id  score_x  score_y
0   1       23       23
1   2       24       24
2   3       12       12
3   5       45       45

In [38]:
merged_df= pd.merge(df1, df2, on='id', how='left')
merged_df

   id name  score
0   1  abc   23.0
1   2  pqr   24.0
2   3  xyz   12.0
3   4  lmn    NaN

In [40]:
merged_df= pd.merge(df2, df3, on='id', how='right')
merged_df

   id  score_x  score_y
0   1     23.0       23
1   2     24.0       24
2   3     12.0       12
3   4      NaN       45

In [ ]:
# if two tables has differnet label of common column

In [51]:
df5= pd.DataFrame({'emp_id':[1,2,3,4], 'dept':['Comp', 'IT', 'Civil', 'Comp']})

In [53]:
merged_df= pd.merge(df1, df5, how='inner', left_on='id', right_on='emp_id')
merged_df

   id name  emp_id   dept
0   1  abc       1   Comp
1   2  pqr       2     IT
2   3  xyz       3  Civil
3   4  lmn       4   Comp

In [ ]:

df= df1.merge(df5, how='inner', left_on='id', right_on='emp_id')
df

   id name  emp_id   dept
0   1  abc       1   Comp
1   2  pqr       2     IT
2   3  xyz       3  Civil
3   4  lmn       4   Comp

In [ ]:
# 2. join function
# joins two tables by index value

In [70]:
df1= pd.DataFrame({'sid':[1,2,3,4], 'name':['abc', 'xyz', 'mnp', 'yhu']}, index=[1,2,3,4])
df2= pd.DataFrame({'tid':[1,2,3,5],'marks':[34,78,89,78]}, index=[1,2,3,9])
df3= pd.DataFrame({'nid':[1,2,3,8],'tmarks':[34,78,89,78]}, index=[1,2,3,10])

In [ ]:

df3= df1.join(df2, how='inner')
df3

   sid name  tid  marks
1    1  abc    1     34
2    2  xyz    2     78
3    3  mnp    3     89

In [66]:
df3= df1.join(df2, how='left')
df3

   sid name  tid  marks
1    1  abc  1.0   34.0
2    2  xyz  2.0   78.0
3    3  mnp  3.0   89.0
4    4  yhu  NaN    NaN

In [67]:
df3= df1.join(df2, how='right')
df3

   sid name  tid  marks
1  1.0  abc    1     34
2  2.0  xyz    2     78
3  3.0  mnp    3     89
9  NaN  NaN    5     78

In [ ]:
# join more than two df at a time - we can use only inner and outer joins and left here no  rightjoin becoiz at right there are more than 1 table
# bydefault - left join
df= df1.join([df2, df3])
df

   sid name  tid  marks  nid  tmarks
1  1.0  abc  1.0   34.0  1.0    34.0
2  2.0  xyz  2.0   78.0  2.0    78.0
3  3.0  mnp  3.0   89.0  3.0    89.0
4  4.0  yhu  NaN    NaN  NaN     NaN

In [82]:
df= df1.join([df2, df3], how='outer')
df

    sid name  tid  marks  nid  tmarks
1   1.0  abc  1.0   34.0  1.0    34.0
2   2.0  xyz  2.0   78.0  2.0    78.0
3   3.0  mnp  3.0   89.0  3.0    89.0
4   4.0  yhu  NaN    NaN  NaN     NaN
9   NaN  NaN  5.0   78.0  NaN     NaN
10  NaN  NaN  NaN    NaN  8.0    78.0

In [83]:
df= df1.join([df2, df3], how= 'left')
df

   sid name  tid  marks  nid  tmarks
1  1.0  abc  1.0   34.0  1.0    34.0
2  2.0  xyz  2.0   78.0  2.0    78.0
3  3.0  mnp  3.0   89.0  3.0    89.0
4  4.0  yhu  NaN    NaN  NaN     NaN

In [ ]:
df= df1.join([df2, df3], how= 'inner')
df

   sid name  tid  marks  nid  tmarks
1    1  abc    1     34    1      34
2    2  xyz    2     78    2      78
3    3  mnp    3     89    3      89

In [ ]:
# concat: axis based they are joined 
# axis means row wise join or column wise join 
# axis 0 row wise
# axis 1 column wise

In [74]:
df1

   sid name
1    1  abc
2    2  xyz
3    3  mnp
4    4  yhu

In [75]:
df2

   tid  marks
1    1     34
2    2     78
3    3     89
9    5     78

In [79]:
res = pd.concat([df1, df2], axis=0)
res

   sid name  tid  marks
1  1.0  abc  NaN    NaN
2  2.0  xyz  NaN    NaN
3  3.0  mnp  NaN    NaN
4  4.0  yhu  NaN    NaN
1  NaN  NaN  1.0   34.0
2  NaN  NaN  2.0   78.0
3  NaN  NaN  3.0   89.0
9  NaN  NaN  5.0   78.0

In [80]:
res = pd.concat([df1, df2], axis=1)
res

   sid name  tid  marks
1  1.0  abc  1.0   34.0
2  2.0  xyz  2.0   78.0
3  3.0  mnp  3.0   89.0
4  4.0  yhu  NaN    NaN
9  NaN  NaN  5.0   78.0

In [87]:
df1.describe()

            sid
count  4.000000
mean   2.500000
std    1.290994
min    1.000000
25%    1.750000
50%    2.500000
75%    3.250000
max    4.000000

In [ ]:
# all functions and methods used in pandas series apllicable to dataframe also